### todas las pelis
GET http://localhost:3001/api/peliculas

### AgregarPelicula
POST http://localhost:3001/api/peliculas
Content-Type: application/json  
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6Miwicm9sIjoiQURNSU4iLCJpYXQiOjE3OTEzNzgxMzgsImV4cCI6MTc5MTM4MTczOH0.3eQP05Zw4LR2XcVYMXCTH8RfbHVs0q2Bxm4cGBxU334

{
    "TituloPelicula": "Shrek 0",
    "Duracion": 400,
    "Sinopsis": "Un ogro que vive en un pantano y tiene que salvar a una princesa de un dragón.",
    "CodGenero": 2,
    "Clasificacion": "10/10",
    "Cartelera": "https://example.com/cartelera.jpg",
    "Trailer": "https://example.com/trailer.mp4"
}
### AgregarPelicula
POST http://localhost:3001/api/peliculas
Content-Type: application/json  
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6Miwicm9sIjoiQURNSU4iLCJpYXQiOjE3OTEzNzgxMzgsImV4cCI6MTc5MTM4MTczOH0.3eQP05Zw4LR2XcVYMXCTH8RfbHVs0q2Bxm4cGBxU334

{
    "TituloPelicula": "Las aventuras de Shrek",
    "Duracion": 198,
    "Sinopsis": "Un ogro que vive en un pantano y tiene aventuras.",
    "CodGenero": 2,
    "Clasificacion": "PG-13"
}

### BorrarPelicula
DELETE http://localhost:3001/api/peliculas/1



###  BuscarPorTitulo
GET http://localhost:3001/api/peliculas/buscar?titulo=shr



### BuscarPorGenero
GET http://localhost:3001/api/peliculas/genero/2
