###Obtener listado de salas
GET http://localhost:3001/api/salas

###Obtener una sala
GET http://localhost:3001/api/salas/1

### Sube sala
POST http://localhost:3001/api/salas
Content-Type: application/json  

{
  "NumSala": 2,
  "Capacidad": 100,
  "TipoPantalla": "2D",
  "TipoAsientos": "Reclinables"
}

### Modificar sala
PUT http://localhost:3001/api/salas/2 
Content-Type: application/json

{
  "NumSala": 2,
  "Capacidad": 120,
  "TipoPantalla": "3D",
  "TipoAsientos": "Reclinables"
}


### Modificar sala
PATCH http://localhost:3001/api/salas/2
Content-Type: application/json

{
  "NumSala": 2,
  "TipoPantalla": "3D",
  "TipoAsientos": "SuperSeat"
}

###Borrar
DELETE http://localhost:3001/api/salas/3
